name: teleport_router_annotation
description: Annotations for teleport_router.
version: 0.7.1
homepage: https://github.com/lwj1994/teleport_router
issue_tracker: https://github.com/lwj1994/teleport_router/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
