name: tp_router_generator
description: Code generator for tp_router annotations.
version: 0.0.3
homepage: https://github.com/lwj1994/tp_router

environment:
  sdk: '>=3.0.0 <4.0.0'
dependency_overrides: 
  tp_router_annotation:
    path: ../tp_router_annotation
  
dependencies:
  analyzer: ^8.4.1
  build: ^4.0.3
  glob: ^2.1.0
  source_gen: ^4.1.0
  tp_router_annotation: ^0.0.1

dev_dependencies:
  build_test: 
  test: ^1.24.0
