name: tp_router_generator
description: A build_runner code generator that processes tp_router annotations to generate type-safe routing code for Flutter applications.
version: 0.6.2
homepage: https://github.com/lwj1994/tp_router
repository: https://github.com/lwj1994/tp_router
issue_tracker: https://github.com/lwj1994/tp_router/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^8.4.1
  build: ^4.0.3
  glob: ^2.1.0
  source_gen: ^4.1.0
  tp_router_annotation: ^0.6.2

dev_dependencies:
  build_test: 
  test: ^1.24.0
