name: example
description: Example app demonstrating teleport_router usage.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  teleport_router:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  teleport_router_generator:
    path: ../../teleport_router_generator
  flutter_lints: ^5.0.0

dependency_overrides:
  teleport_router_annotation:
    path: ../../teleport_router_annotation
  teleport_router_generator:
    path: ../../teleport_router_generator

flutter:
  uses-material-design: true