name: example
description: Example app demonstrating tp_router usage.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tp_router:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  tp_router_generator:
    path: ../../tp_router_generator
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true