name: tp_router_generator_example
description: Example demonstrating tp_router_generator usage
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tp_router: any

  tp_router_annotation: any
dev_dependencies:
  build_runner: any
  tp_router_generator: any
